name: Cross-Platform Build Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            build-command: npm run build:win
          - os: macos-latest
            build-command: npm run build:mac
          - os: ubuntu-latest
            build-command: npm run build:linux

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Updated to Node 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: ${{ matrix.build-command }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-tracker-${{ matrix.os }}
          path: dist/
          retention-days: 7
