name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Windows executable
      run: npx rimraf dist && npx electron-builder --win portable --publish never
      
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/*.exe
        
  build-mac:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build macOS DMG
      run: npx rimraf dist && npx electron-builder --mac dmg --publish never
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
      
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: mac-build
        path: dist/*.dmg
        
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Linux AppImage
      run: npx rimraf dist && npx electron-builder --linux AppImage --publish never
      
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: dist/*.AppImage
        
  create-release:
    needs: [build-windows, build-mac, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Extract changelog for this version
      id: changelog
      run: |
        VERSION="${{ steps.get_version.outputs.VERSION }}"
        CHANGELOG=$(awk "/## \[$VERSION\]/{flag=1; next} /## \[/{flag=0} flag" CHANGELOG.md)
        echo "BODY<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-build
        path: ./dist-windows
        
    - name: Download macOS artifact
      uses: actions/download-artifact@v4
      with:
        name: mac-build
        path: ./dist-mac
        
    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-build
        path: ./dist-linux
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Portfolio Tracker v${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Portfolio Tracker v${{ steps.get_version.outputs.VERSION }}
          
          ${{ steps.changelog.outputs.BODY }}
          
          ### Downloads
          - **Windows**: `Portfolio Tracker ${{ steps.get_version.outputs.VERSION }}.exe` - Portable executable
          - **macOS**: `Portfolio Tracker-${{ steps.get_version.outputs.VERSION }}.dmg` - Disk image
          - **Linux**: `Portfolio Tracker-${{ steps.get_version.outputs.VERSION }}.AppImage` - AppImage package
          
          ### Installation
          - **Windows**: Download and run the .exe file - no installation needed
          - **macOS**: Download the .dmg, open it, and drag the app to Applications
          - **Linux**: Download the AppImage, make it executable (`chmod +x`), and run
        files: |
          dist-windows/*.exe
          dist-mac/*.dmg
          dist-linux/*.AppImage
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}