name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application (Windows)
      if: matrix.os == 'windows-latest'
      run: npx rimraf dist && npx electron-builder --win portable --publish never
      
    - name: Build application (macOS)
      if: matrix.os == 'macos-latest'
      run: npx rimraf dist && npx electron-builder --mac dmg --publish never
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
        
    - name: Build application (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: npx rimraf dist && npx electron-builder --linux AppImage --publish never
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.node-version == 20
      with:
        name: ${{ matrix.os }}-node${{ matrix.node-version }}-build
        path: |
          dist/*.exe
          dist/*.dmg
          dist/*.AppImage
        retention-days: 7