name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check dependencies are installed
      run: npm ls
      
    - name: Verify Electron installation
      run: npx electron --version
      
    - name: Test application can start (headless)
      if: matrix.os == 'ubuntu-latest'
      run: |
        export DISPLAY=:99.0
        npx electron . --version
      env:
        CI: true